/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PhysicsEngine {
  export type SectorStruct = {
    id: BigNumberish;
    owner: AddressLike;
    energyRate: BigNumberish;
    computeRate: BigNumberish;
    dataRate: BigNumberish;
    lastClaimed: BigNumberish;
    level: BigNumberish;
    active: boolean;
  };

  export type SectorStructOutput = [
    id: bigint,
    owner: string,
    energyRate: bigint,
    computeRate: bigint,
    dataRate: bigint,
    lastClaimed: bigint,
    level: bigint,
    active: boolean
  ] & {
    id: bigint;
    owner: string;
    energyRate: bigint;
    computeRate: bigint;
    dataRate: bigint;
    lastClaimed: bigint;
    level: bigint;
    active: boolean;
  };
}

export interface PhysicsEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_COMPUTE_RATE"
      | "BASE_DATA_RATE"
      | "BASE_ENERGY_RATE"
      | "DEFAULT_ADMIN_ROLE"
      | "KEEPER_ROLE"
      | "MAX_SECTORS"
      | "TICK_INTERVAL"
      | "abandonSector"
      | "claimSector"
      | "compute"
      | "data"
      | "energy"
      | "getActiveSectors"
      | "getRoleAdmin"
      | "getSector"
      | "getSectorYield"
      | "getWorldState"
      | "grantRole"
      | "hasRole"
      | "intentMarket"
      | "lastTickTimestamp"
      | "processTick"
      | "renounceRole"
      | "revokeRole"
      | "sectorCount"
      | "sectors"
      | "supportsInterface"
      | "tickCount"
      | "upgradeSector"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ResourcesGenerated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SectorClaimed"
      | "SectorUpgraded"
      | "TickProcessed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_COMPUTE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_DATA_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_ENERGY_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SECTORS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICK_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "abandonSector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSector",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "compute", values?: undefined): string;
  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(functionFragment: "energy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getActiveSectors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSectorYield",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorldState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "intentMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastTickTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processTick",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sectorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sectors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tickCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeSector",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_COMPUTE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_DATA_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_ENERGY_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SECTORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICK_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "abandonSector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "compute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "energy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSector", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSectorYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorldState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "intentMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastTickTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sectorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sectors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeSector",
    data: BytesLike
  ): Result;
}

export namespace ResourcesGeneratedEvent {
  export type InputTuple = [
    sectorId: BigNumberish,
    energy: BigNumberish,
    compute: BigNumberish,
    data: BigNumberish
  ];
  export type OutputTuple = [
    sectorId: bigint,
    energy: bigint,
    compute: bigint,
    data: bigint
  ];
  export interface OutputObject {
    sectorId: bigint;
    energy: bigint;
    compute: bigint;
    data: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SectorClaimedEvent {
  export type InputTuple = [sectorId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [sectorId: bigint, owner: string];
  export interface OutputObject {
    sectorId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SectorUpgradedEvent {
  export type InputTuple = [sectorId: BigNumberish, newLevel: BigNumberish];
  export type OutputTuple = [sectorId: bigint, newLevel: bigint];
  export interface OutputObject {
    sectorId: bigint;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TickProcessedEvent {
  export type InputTuple = [
    tickNumber: BigNumberish,
    sectorsClaimed: BigNumberish
  ];
  export type OutputTuple = [tickNumber: bigint, sectorsClaimed: bigint];
  export interface OutputObject {
    tickNumber: bigint;
    sectorsClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PhysicsEngine extends BaseContract {
  connect(runner?: ContractRunner | null): PhysicsEngine;
  waitForDeployment(): Promise<this>;

  interface: PhysicsEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_COMPUTE_RATE: TypedContractMethod<[], [bigint], "view">;

  BASE_DATA_RATE: TypedContractMethod<[], [bigint], "view">;

  BASE_ENERGY_RATE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  KEEPER_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_SECTORS: TypedContractMethod<[], [bigint], "view">;

  TICK_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  abandonSector: TypedContractMethod<
    [sectorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimSector: TypedContractMethod<
    [sectorId: BigNumberish, swarmAccount: AddressLike],
    [void],
    "nonpayable"
  >;

  compute: TypedContractMethod<[], [string], "view">;

  data: TypedContractMethod<[], [string], "view">;

  energy: TypedContractMethod<[], [string], "view">;

  getActiveSectors: TypedContractMethod<
    [],
    [PhysicsEngine.SectorStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSector: TypedContractMethod<
    [sectorId: BigNumberish],
    [PhysicsEngine.SectorStructOutput],
    "view"
  >;

  getSectorYield: TypedContractMethod<
    [sectorId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        energyYield: bigint;
        computeYield: bigint;
        dataYield: bigint;
      }
    ],
    "view"
  >;

  getWorldState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        _tickCount: bigint;
        _lastTick: bigint;
        _sectorCount: bigint;
        _energySupply: bigint;
        _computeSupply: bigint;
        _dataSupply: bigint;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  intentMarket: TypedContractMethod<[], [string], "view">;

  lastTickTimestamp: TypedContractMethod<[], [bigint], "view">;

  processTick: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sectorCount: TypedContractMethod<[], [bigint], "view">;

  sectors: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        owner: string;
        energyRate: bigint;
        computeRate: bigint;
        dataRate: bigint;
        lastClaimed: bigint;
        level: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tickCount: TypedContractMethod<[], [bigint], "view">;

  upgradeSector: TypedContractMethod<
    [sectorId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_COMPUTE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_DATA_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BASE_ENERGY_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEEPER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SECTORS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TICK_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "abandonSector"
  ): TypedContractMethod<[sectorId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimSector"
  ): TypedContractMethod<
    [sectorId: BigNumberish, swarmAccount: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "compute"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "data"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "energy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveSectors"
  ): TypedContractMethod<[], [PhysicsEngine.SectorStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSector"
  ): TypedContractMethod<
    [sectorId: BigNumberish],
    [PhysicsEngine.SectorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSectorYield"
  ): TypedContractMethod<
    [sectorId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        energyYield: bigint;
        computeYield: bigint;
        dataYield: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorldState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        _tickCount: bigint;
        _lastTick: bigint;
        _sectorCount: bigint;
        _energySupply: bigint;
        _computeSupply: bigint;
        _dataSupply: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "intentMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastTickTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "processTick"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sectorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sectors"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        owner: string;
        energyRate: bigint;
        computeRate: bigint;
        dataRate: bigint;
        lastClaimed: bigint;
        level: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tickCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeSector"
  ): TypedContractMethod<[sectorId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ResourcesGenerated"
  ): TypedContractEvent<
    ResourcesGeneratedEvent.InputTuple,
    ResourcesGeneratedEvent.OutputTuple,
    ResourcesGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SectorClaimed"
  ): TypedContractEvent<
    SectorClaimedEvent.InputTuple,
    SectorClaimedEvent.OutputTuple,
    SectorClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SectorUpgraded"
  ): TypedContractEvent<
    SectorUpgradedEvent.InputTuple,
    SectorUpgradedEvent.OutputTuple,
    SectorUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "TickProcessed"
  ): TypedContractEvent<
    TickProcessedEvent.InputTuple,
    TickProcessedEvent.OutputTuple,
    TickProcessedEvent.OutputObject
  >;

  filters: {
    "ResourcesGenerated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ResourcesGeneratedEvent.InputTuple,
      ResourcesGeneratedEvent.OutputTuple,
      ResourcesGeneratedEvent.OutputObject
    >;
    ResourcesGenerated: TypedContractEvent<
      ResourcesGeneratedEvent.InputTuple,
      ResourcesGeneratedEvent.OutputTuple,
      ResourcesGeneratedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SectorClaimed(uint256,address)": TypedContractEvent<
      SectorClaimedEvent.InputTuple,
      SectorClaimedEvent.OutputTuple,
      SectorClaimedEvent.OutputObject
    >;
    SectorClaimed: TypedContractEvent<
      SectorClaimedEvent.InputTuple,
      SectorClaimedEvent.OutputTuple,
      SectorClaimedEvent.OutputObject
    >;

    "SectorUpgraded(uint256,uint8)": TypedContractEvent<
      SectorUpgradedEvent.InputTuple,
      SectorUpgradedEvent.OutputTuple,
      SectorUpgradedEvent.OutputObject
    >;
    SectorUpgraded: TypedContractEvent<
      SectorUpgradedEvent.InputTuple,
      SectorUpgradedEvent.OutputTuple,
      SectorUpgradedEvent.OutputObject
    >;

    "TickProcessed(uint256,uint256)": TypedContractEvent<
      TickProcessedEvent.InputTuple,
      TickProcessedEvent.OutputTuple,
      TickProcessedEvent.OutputObject
    >;
    TickProcessed: TypedContractEvent<
      TickProcessedEvent.InputTuple,
      TickProcessedEvent.OutputTuple,
      TickProcessedEvent.OutputObject
    >;
  };
}
