/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swarmNftSol from "./SwarmNFT.sol";
export type { swarmNftSol };
export type { SwarmAccount } from "./SwarmAccount";
