/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IntentMarket {
  export type IntentStruct = {
    id: BigNumberish;
    creator: AddressLike;
    intentType: BigNumberish;
    tokenIn: AddressLike;
    tokenOut: AddressLike;
    amountIn: BigNumberish;
    amountOut: BigNumberish;
    minFill: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    extraData: BytesLike;
  };

  export type IntentStructOutput = [
    id: bigint,
    creator: string,
    intentType: bigint,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint,
    amountOut: bigint,
    minFill: bigint,
    deadline: bigint,
    status: bigint,
    extraData: string
  ] & {
    id: bigint;
    creator: string;
    intentType: bigint;
    tokenIn: string;
    tokenOut: string;
    amountIn: bigint;
    amountOut: bigint;
    minFill: bigint;
    deadline: bigint;
    status: bigint;
    extraData: string;
  };

  export type QuoteStruct = {
    intentId: BigNumberish;
    solver: AddressLike;
    fillAmount: BigNumberish;
    receiveAmount: BigNumberish;
    accepted: boolean;
  };

  export type QuoteStructOutput = [
    intentId: bigint,
    solver: string,
    fillAmount: bigint,
    receiveAmount: bigint,
    accepted: boolean
  ] & {
    intentId: bigint;
    solver: string;
    fillAmount: bigint;
    receiveAmount: bigint;
    accepted: boolean;
  };
}

export interface IntentMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptQuote"
      | "cancelIntent"
      | "createIntent"
      | "expireStaleIntents"
      | "getActiveIntents"
      | "getIntent"
      | "getQuotes"
      | "intents"
      | "physicsEngine"
      | "quotes"
      | "submitQuote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IntentCancelled"
      | "IntentCreated"
      | "IntentExpired"
      | "IntentFilled"
      | "QuoteSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptQuote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "expireStaleIntents",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveIntents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "intents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "physicsEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitQuote",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireStaleIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getQuotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "intents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "physicsEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitQuote",
    data: BytesLike
  ): Result;
}

export namespace IntentCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    intentType: BigNumberish,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    intentType: bigint,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    intentType: bigint;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentExpiredEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentFilledEvent {
  export type InputTuple = [
    id: BigNumberish,
    solver: AddressLike,
    fillAmount: BigNumberish,
    receiveAmount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    solver: string,
    fillAmount: bigint,
    receiveAmount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    solver: string;
    fillAmount: bigint;
    receiveAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteSubmittedEvent {
  export type InputTuple = [
    intentId: BigNumberish,
    solver: AddressLike,
    fillAmount: BigNumberish
  ];
  export type OutputTuple = [
    intentId: bigint,
    solver: string,
    fillAmount: bigint
  ];
  export interface OutputObject {
    intentId: bigint;
    solver: string;
    fillAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntentMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IntentMarket;
  waitForDeployment(): Promise<this>;

  interface: IntentMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptQuote: TypedContractMethod<
    [intentId: BigNumberish, quoteIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelIntent: TypedContractMethod<
    [intentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createIntent: TypedContractMethod<
    [
      intentType: BigNumberish,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  expireStaleIntents: TypedContractMethod<
    [intentIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getActiveIntents: TypedContractMethod<
    [],
    [IntentMarket.IntentStructOutput[]],
    "view"
  >;

  getIntent: TypedContractMethod<
    [intentId: BigNumberish],
    [IntentMarket.IntentStructOutput],
    "view"
  >;

  getQuotes: TypedContractMethod<
    [intentId: BigNumberish],
    [IntentMarket.QuoteStructOutput[]],
    "view"
  >;

  intents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        creator: string;
        intentType: bigint;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        minFill: bigint;
        deadline: bigint;
        status: bigint;
        extraData: string;
      }
    ],
    "view"
  >;

  physicsEngine: TypedContractMethod<[], [string], "view">;

  quotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        intentId: bigint;
        solver: string;
        fillAmount: bigint;
        receiveAmount: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;

  submitQuote: TypedContractMethod<
    [
      intentId: BigNumberish,
      fillAmount: BigNumberish,
      receiveAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptQuote"
  ): TypedContractMethod<
    [intentId: BigNumberish, quoteIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelIntent"
  ): TypedContractMethod<[intentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<
    [
      intentType: BigNumberish,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOut: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expireStaleIntents"
  ): TypedContractMethod<[intentIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveIntents"
  ): TypedContractMethod<[], [IntentMarket.IntentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getIntent"
  ): TypedContractMethod<
    [intentId: BigNumberish],
    [IntentMarket.IntentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuotes"
  ): TypedContractMethod<
    [intentId: BigNumberish],
    [IntentMarket.QuoteStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "intents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        creator: string;
        intentType: bigint;
        tokenIn: string;
        tokenOut: string;
        amountIn: bigint;
        amountOut: bigint;
        minFill: bigint;
        deadline: bigint;
        status: bigint;
        extraData: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "physicsEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean] & {
        intentId: bigint;
        solver: string;
        fillAmount: bigint;
        receiveAmount: bigint;
        accepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitQuote"
  ): TypedContractMethod<
    [
      intentId: BigNumberish,
      fillAmount: BigNumberish,
      receiveAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IntentCancelled"
  ): TypedContractEvent<
    IntentCancelledEvent.InputTuple,
    IntentCancelledEvent.OutputTuple,
    IntentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "IntentCreated"
  ): TypedContractEvent<
    IntentCreatedEvent.InputTuple,
    IntentCreatedEvent.OutputTuple,
    IntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IntentExpired"
  ): TypedContractEvent<
    IntentExpiredEvent.InputTuple,
    IntentExpiredEvent.OutputTuple,
    IntentExpiredEvent.OutputObject
  >;
  getEvent(
    key: "IntentFilled"
  ): TypedContractEvent<
    IntentFilledEvent.InputTuple,
    IntentFilledEvent.OutputTuple,
    IntentFilledEvent.OutputObject
  >;
  getEvent(
    key: "QuoteSubmitted"
  ): TypedContractEvent<
    QuoteSubmittedEvent.InputTuple,
    QuoteSubmittedEvent.OutputTuple,
    QuoteSubmittedEvent.OutputObject
  >;

  filters: {
    "IntentCancelled(uint256)": TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;
    IntentCancelled: TypedContractEvent<
      IntentCancelledEvent.InputTuple,
      IntentCancelledEvent.OutputTuple,
      IntentCancelledEvent.OutputObject
    >;

    "IntentCreated(uint256,address,uint8,uint256,uint256)": TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;
    IntentCreated: TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;

    "IntentExpired(uint256)": TypedContractEvent<
      IntentExpiredEvent.InputTuple,
      IntentExpiredEvent.OutputTuple,
      IntentExpiredEvent.OutputObject
    >;
    IntentExpired: TypedContractEvent<
      IntentExpiredEvent.InputTuple,
      IntentExpiredEvent.OutputTuple,
      IntentExpiredEvent.OutputObject
    >;

    "IntentFilled(uint256,address,uint256,uint256)": TypedContractEvent<
      IntentFilledEvent.InputTuple,
      IntentFilledEvent.OutputTuple,
      IntentFilledEvent.OutputObject
    >;
    IntentFilled: TypedContractEvent<
      IntentFilledEvent.InputTuple,
      IntentFilledEvent.OutputTuple,
      IntentFilledEvent.OutputObject
    >;

    "QuoteSubmitted(uint256,address,uint256)": TypedContractEvent<
      QuoteSubmittedEvent.InputTuple,
      QuoteSubmittedEvent.OutputTuple,
      QuoteSubmittedEvent.OutputObject
    >;
    QuoteSubmitted: TypedContractEvent<
      QuoteSubmittedEvent.InputTuple,
      QuoteSubmittedEvent.OutputTuple,
      QuoteSubmittedEvent.OutputObject
    >;
  };
}
