/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwarmAccount,
  ISwarmAccountInterface,
} from "../../../../contracts/swarm/SwarmNFT.sol/ISwarmAccount";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "architect",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "swarmId",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        internalType: "bool",
        name: "authorized",
        type: "bool",
      },
    ],
    name: "setExecutor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwarmAccount__factory {
  static readonly abi = _abi;
  static createInterface(): ISwarmAccountInterface {
    return new Interface(_abi) as ISwarmAccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISwarmAccount {
    return new Contract(address, _abi, runner) as unknown as ISwarmAccount;
  }
}
